#  which() function 

The which() function in R returns the position or the index of the value which satisfies the given condition. The Which() function in R gives you the position of the value in a logical vector. The position can be of anything like rows, columns and even vector as well

### Syntax of which() function

which(): The which function in R returns the position of the values in the logical vector.

**which(x,arr.ind = F,useNames = F)**

* **X =** An input logical vector.
* **Arr.ind =** Returns the array indices if x is an array.
* **useNames =**Indicates the dimension names of an array.

In [1]:
which(letters=="p")

[1] 16

In [3]:
which(letters=="o")

[1] 15

In [4]:
which(LETTERS=="P")

[1] 16

In [8]:
which(letters=="m")

[1] 13

#### Using the which() function with vectors

In [1]:
df<- c(5,4,3,2,1)
which(df ==2)

[1] 4

In [3]:
dfa <- c("Kon","Shan","James","Johns")

In [4]:
which(dfa=="Smith")

integer(0)

In [5]:
which(df==5)

[1] 1

In [9]:
which(df==1)

[1] 5

In [10]:
which(df>2)

[1] 1 2 3

#### Using the which() function with dataframes

In [6]:
df<-datasets::BOD
df

Time demand
1 1     8.3  
2 2    10.3  
3 3    19.0  
4 4    16.0  
5 5    15.6  
6 7    19.8

In [7]:
which(df['demand']=='10.3')

[1] 2

In [11]:
which(df$demand== 10.3)

[1] 2

In [12]:
df<-datasets::iris
df

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
1   5.1          3.5         1.4          0.2         setosa   
2   4.9          3.0         1.4          0.2         setosa   
3   4.7          3.2         1.3          0.2         setosa   
4   4.6          3.1         1.5          0.2         setosa   
5   5.0          3.6         1.4          0.2         setosa   
6   5.4          3.9         1.7          0.4         setosa   
7   4.6          3.4         1.4          0.3         setosa   
8   5.0          3.4         1.5          0.2         setosa   
9   4.4          2.9         1.4          0.2         setosa   
10  4.9          3.1         1.5          0.1         setosa   
11  5.4          3.7         1.5          0.2         setosa   
12  4.8          3.4         1.6          0.2         setosa   
13  4.8          3.0         1.4          0.1         setosa   
14  4.3          3.0         1.1          0.1         setosa   
15  5.8          4.0         1.2          0.2         setosa   
16  5.7          4.4         1.5          0.4         setosa   
17  5.4          3.9         1.3          0.4         setosa   
18  5.1          3.5         1.4          0.3         setosa   
19  5.7          3.8         1.7          0.3         setosa   
20  5.1          3.8         1.5          0.3         setosa   
21  5.4          3.4         1.7          0.2         setosa   
22  5.1          3.7         1.5          0.4         setosa   
23  4.6          3.6         1.0          0.2         setosa   
24  5.1          3.3         1.7          0.5         setosa   
25  4.8          3.4         1.9          0.2         setosa   
26  5.0          3.0         1.6          0.2         setosa   
27  5.0          3.4         1.6          0.4         setosa   
28  5.2          3.5         1.5          0.2         setosa   
29  5.2          3.4         1.4          0.2         setosa   
30  4.7          3.2         1.6          0.2         setosa   
... ...          ...         ...          ...         ...      
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

**is.numeric()** function in R Language is used to check if the object passed to it as argument is of numeric type.

In [15]:
test<-which(sapply(df,is.numeric))
colnames(df)[test]
#test

[1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"

In [16]:
dfa <- read.csv('marvel-wikia-data.csv')

In [18]:
testa <- which(sapply(dfa,is.numeric))
colnames(dfa)[testa]

[1] "page_id"     "APPEARANCES" "Year"

In [19]:
testa


page_id APPEARANCES        Year 
          1          11          13

#### Which function with Matrix in R

In [24]:
df<-matrix(rep(c(1,0,1),4),nrow = 4)
df

[,1] [,2] [,3]
[1,] 1    0    1   
[2,] 0    1    1   
[3,] 1    1    0   
[4,] 1    0    1

In [17]:
which(df==0,arr.ind = T)

row col
[1,] 2   1  
[2,] 1   2  
[3,] 4   2  
[4,] 3   3

In [18]:
datasets::npk

block N P K yield
1  1     0 1 1 49.5 
2  1     1 1 0 62.8 
3  1     0 0 0 46.8 
4  1     1 0 1 57.0 
5  2     1 0 0 59.8 
6  2     1 1 1 58.5 
7  2     0 0 1 55.5 
8  2     0 1 0 56.0 
9  3     0 1 0 62.8 
10 3     1 1 1 55.8 
11 3     1 0 0 69.5 
12 3     0 0 1 55.0 
13 4     1 0 0 62.0 
14 4     1 1 1 48.8 
15 4     0 0 1 45.5 
16 4     0 1 0 44.2 
17 5     1 1 0 52.0 
18 5     0 0 0 51.5 
19 5     1 0 1 49.8 
20 5     0 1 1 48.8 
21 6     1 0 1 57.2 
22 6     1 1 0 59.0 
23 6     0 1 1 53.2 
24 6     0 0 0 56.0

In [19]:
which(npk$yield == 62)

[1] 13

In [20]:
which((npk$yield == 48.8) & (npk$N == 1))

[1] 14

In [21]:
which(npk$yield == max(npk$yield))

[1] 11

# Exploring Categorical Variables

In [22]:
df <- datasets::iris

In [23]:
df

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
1   5.1          3.5         1.4          0.2         setosa   
2   4.9          3.0         1.4          0.2         setosa   
3   4.7          3.2         1.3          0.2         setosa   
4   4.6          3.1         1.5          0.2         setosa   
5   5.0          3.6         1.4          0.2         setosa   
6   5.4          3.9         1.7          0.4         setosa   
7   4.6          3.4         1.4          0.3         setosa   
8   5.0          3.4         1.5          0.2         setosa   
9   4.4          2.9         1.4          0.2         setosa   
10  4.9          3.1         1.5          0.1         setosa   
11  5.4          3.7         1.5          0.2         setosa   
12  4.8          3.4         1.6          0.2         setosa   
13  4.8          3.0         1.4          0.1         setosa   
14  4.3          3.0         1.1          0.1         setosa   
15  5.8          4.0         1.2          0.2         setosa   
16  5.7          4.4         1.5          0.4         setosa   
17  5.4          3.9         1.3          0.4         setosa   
18  5.1          3.5         1.4          0.3         setosa   
19  5.7          3.8         1.7          0.3         setosa   
20  5.1          3.8         1.5          0.3         setosa   
21  5.4          3.4         1.7          0.2         setosa   
22  5.1          3.7         1.5          0.4         setosa   
23  4.6          3.6         1.0          0.2         setosa   
24  5.1          3.3         1.7          0.5         setosa   
25  4.8          3.4         1.9          0.2         setosa   
26  5.0          3.0         1.6          0.2         setosa   
27  5.0          3.4         1.6          0.4         setosa   
28  5.2          3.5         1.5          0.2         setosa   
29  5.2          3.4         1.4          0.2         setosa   
30  4.7          3.2         1.6          0.2         setosa   
... ...          ...         ...          ...         ...      
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [24]:
#Returns the number of occurrences of data points  
table(iris$Sepal.Length)


4.3 4.4 4.5 4.6 4.7 4.8 4.9   5 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9   6 6.1 6.2 
  1   3   1   4   2   5   6  10   9   4   1   6   7   6   8   7   3   6   6   4 
6.3 6.4 6.5 6.6 6.7 6.8 6.9   7 7.1 7.2 7.3 7.4 7.6 7.7 7.9 
  9   7   5   2   8   3   4   1   1   3   1   1   1   4   1 

In [25]:
#Returns the number of occurrences of data points
table(iris$Petal.Width)


0.1 0.2 0.3 0.4 0.5 0.6   1 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9   2 2.1 2.2 2.3 
  5  29   7   7   1   1   7   3   5  13   8  12   4   2  12   5   6   6   3   8 
2.4 2.5 
  3   3 

In [26]:
#Returns the number of occurrences of data points
table(iris$Species)


    setosa versicolor  virginica 
        50         50         50 

As we know R is supreme in data analysis, it can also perform the calculations of the table proportions directly with the help of a function prop.table().

In [28]:
#Assigning the data
props_data <- table(iris$Species)

In [29]:
#Calculates the proportions of categories 
props_data <- prop.table(props_data) * 100

In [30]:
props_data


    setosa versicolor  virginica 
  33.33333   33.33333   33.33333 

In [31]:
#rounds off the decimal values to standard values
round(props_data,1)


    setosa versicolor  virginica 
      33.3       33.3       33.3 

# Handling Missing Values in R – Omit() function

**syntax of na.omit()**

In [32]:
na.omit(data)

function (..., list = character(), package = NULL, lib.loc = NULL, 
    verbose = getOption("verbose"), envir = .GlobalEnv, overwrite = TRUE) 
{
    fileExt <- function(x) {
        db <- grepl("\\.[^.]+\\.(gz|bz2|xz)$", x)
        ans <- sub(".*\\.", "", x)
        ans[db] <- sub(".*\\.([^.]+\\.)(gz|bz2|xz)$", "\\1\\2", 
            x[db])
        ans
    }
    names <- c(as.character(substitute(list(...))[-1L]), list)
    if (!is.null(package)) {
        if (!is.character(package)) 
            stop("'package' must be a character string or NULL")
        if (any(package %in% "base")) 
            warning("datasets have been moved from package 'base' to package 'datasets'")
        if (any(package %in% "stats")) 
            warning("datasets have been moved from package 'stats' to package 'datasets'")
        package[package %in% c("base", "stats")] <- "datasets"
    }
    paths <- find.package(package, lib.loc, verbose = verbose)
    if (is.null(lib.loc)) 
        paths <- c(path.package(package, TRUE), if (!length(package)) getwd(), 
            paths)
    paths <- unique(normalizePath(paths[file.exists(paths)]))
    paths <- paths[dir.exists(file.path(paths, "data"))]
    dataExts <- tools:::.make_file_exts("data")
    if (length(names) == 0L) {
        db <- matrix(character(), nrow = 0L, ncol = 4L)
        for (path in paths) {
            entries <- NULL
            packageName <- if (file_test("-f", file.path(path, 
                "DESCRIPTION"))) 
                basename(path)
            else "."
            if (file_test("-f", INDEX <- file.path(path, "Meta", 
                "data.rds"))) {
                entries <- readRDS(INDEX)
            }
            else {
                dataDir <- file.path(path, "data")
                entries <- tools::list_files_with_type(dataDir, 
                  "data")
                if (length(entries)) {
                  entries <- unique(tools::file_path_sans_ext(basename(entries)))
                  entries <- cbind(entries, "")
                }
            }
            if (NROW(entries)) {
                if (is.matrix(entries) && ncol(entries) == 2L) 
                  db <- rbind(db, cbind(packageName, dirname(path), 
                    entries))
                else warning(gettextf("data index for package %s is invalid and will be ignored", 
                  sQuote(packageName)), domain = NA, call. = FALSE)
            }
        }
        colnames(db) <- c("Package", "LibPath", "Item", "Title")
        footer <- if (missing(package)) 
            paste0("Use ", sQuote(paste("data(package =", ".packages(all.available = TRUE))")), 
                "\n", "to list the data sets in all *available* packages.")
        else NULL
        y <- list(title = "Data sets", header = NULL, results = db, 
            footer = footer)
        class(y) <- "packageIQR"
        return(y)
    }
    paths <- file.path(paths, "data")
    for (name in names) {
        found <- FALSE
        for (p in paths) {
            tmp_env <- if (overwrite) 
                envir
            else new.env()
            if (file_test("-f", file.path(p, "Rdata.rds"))) {
                rds <- readRDS(file.path(p, "Rdata.rds"))
                if (name %in% names(rds)) {
                  found <- TRUE
                  if (verbose) 
                    message(sprintf("name=%s:\t found in Rdata.rds", 
                      name), domain = NA)
                  thispkg <- sub(".*/([^/]*)/data$", "\\1", p)
                  thispkg <- sub("_.*$", "", thispkg)
                  thispkg <- paste0("package:", thispkg)
                  objs <- rds[[name]]
                  lazyLoad(file.path(p, "Rdata"), envir = tmp_env, 
                    filter = function(x) x %in% objs)
                  break
                }
                else if (verbose) 
                  message(sprintf("name=%s:\t NOT found in names() of Rdata.rds, i.e.,\n\t%s\n", 
                    name, paste(names(rds), collapse = ",")

In [34]:
#Creates a vector with NA values in it
df <- c(34,'We25',67,NA,56,87,NA,34,56)

In [35]:
na.omit(df)

[1] "34"   "We25" "67"   "56"   "87"   "34"   "56"  
attr(,"na.action")
[1] 4 7
attr(,"class")
[1] "omit"

In [36]:
df <- c(34,67,NA,56,87,NA,34,56)

In [37]:
df

[1] 34 67 NA 56 87 NA 34 56

#### na.omit() function with a dataframe

In [38]:
#Importing the dataset
df <- datasets::airquality

In [39]:
df

Ozone Solar.R Wind Temp Month Day
1    41   190      7.4 67   5      1 
2    36   118      8.0 72   5      2 
3    12   149     12.6 74   5      3 
4    18   313     11.5 62   5      4 
5    NA    NA     14.3 56   5      5 
6    28    NA     14.9 66   5      6 
7    23   299      8.6 65   5      7 
8    19    99     13.8 59   5      8 
9     8    19     20.1 61   5      9 
10   NA   194      8.6 69   5     10 
11    7    NA      6.9 74   5     11 
12   16   256      9.7 69   5     12 
13   11   290      9.2 66   5     13 
14   14   274     10.9 68   5     14 
15   18    65     13.2 58   5     15 
16   14   334     11.5 64   5     16 
17   34   307     12.0 66   5     17 
18    6    78     18.4 57   5     18 
19   30   322     11.5 68   5     19 
20   11    44      9.7 62   5     20 
21    1     8      9.7 59   5     21 
22   11   320     16.6 73   5     22 
23    4    25      9.7 61   5     23 
24   32    92     12.0 61   5     24 
25   NA    66     16.6 57   5     25 
26   NA   266     14.9 58   5     26 
27   NA    NA      8.0 57   5     27 
28   23    13     12.0 67   5     28 
29   45   252     14.9 81   5     29 
30  115   223      5.7 79   5     30 
... ...   ...     ...  ...  ...   ...
124 96    167      6.9 91   9      1 
125 78    197      5.1 92   9      2 
126 73    183      2.8 93   9      3 
127 91    189      4.6 93   9      4 
128 47     95      7.4 87   9      5 
129 32     92     15.5 84   9      6 
130 20    252     10.9 80   9      7 
131 23    220     10.3 78   9      8 
132 21    230     10.9 75   9      9 
133 24    259      9.7 73   9     10 
134 44    236     14.9 81   9     11 
135 21    259     15.5 76   9     12 
136 28    238      6.3 77   9     13 
137  9     24     10.9 71   9     14 
138 13    112     11.5 71   9     15 
139 46    237      6.9 78   9     16 
140 18    224     13.8 67   9     17 
141 13     27     10.3 76   9     18 
142 24    238     10.3 68   9     19 
143 16    201      8.0 82   9     20 
144 13    238     12.6 64   9     21 
145 23     14      9.2 71   9     22 
146 36    139     10.3 81   9     23 
147  7     49     10.3 69   9     24 
148 14     20     16.6 63   9     25 
149 30    193      6.9 70   9     26 
150 NA    145     13.2 77   9     27 
151 14    191     14.3 75   9     28 
152 18    131      8.0 76   9     29 
153 20    223     11.5 68   9     30

In [40]:
na.omit(df)

Ozone Solar.R Wind Temp Month Day
1    41   190      7.4 67   5      1 
2    36   118      8.0 72   5      2 
3    12   149     12.6 74   5      3 
4    18   313     11.5 62   5      4 
7    23   299      8.6 65   5      7 
8    19    99     13.8 59   5      8 
9     8    19     20.1 61   5      9 
12   16   256      9.7 69   5     12 
13   11   290      9.2 66   5     13 
14   14   274     10.9 68   5     14 
15   18    65     13.2 58   5     15 
16   14   334     11.5 64   5     16 
17   34   307     12.0 66   5     17 
18    6    78     18.4 57   5     18 
19   30   322     11.5 68   5     19 
20   11    44      9.7 62   5     20 
21    1     8      9.7 59   5     21 
22   11   320     16.6 73   5     22 
23    4    25      9.7 61   5     23 
24   32    92     12.0 61   5     24 
28   23    13     12.0 67   5     28 
29   45   252     14.9 81   5     29 
30  115   223      5.7 79   5     30 
31   37   279      7.4 76   5     31 
38   29   127      9.7 82   6      7 
40   71   291     13.8 90   6      9 
41   39   323     11.5 87   6     10 
44   23   148      8.0 82   6     13 
47   21   191     14.9 77   6     16 
48   37   284     20.7 72   6     17 
... ...   ...     ...  ...  ...   ...
123 85    188      6.3 94   8     31 
124 96    167      6.9 91   9      1 
125 78    197      5.1 92   9      2 
126 73    183      2.8 93   9      3 
127 91    189      4.6 93   9      4 
128 47     95      7.4 87   9      5 
129 32     92     15.5 84   9      6 
130 20    252     10.9 80   9      7 
131 23    220     10.3 78   9      8 
132 21    230     10.9 75   9      9 
133 24    259      9.7 73   9     10 
134 44    236     14.9 81   9     11 
135 21    259     15.5 76   9     12 
136 28    238      6.3 77   9     13 
137  9     24     10.9 71   9     14 
138 13    112     11.5 71   9     15 
139 46    237      6.9 78   9     16 
140 18    224     13.8 67   9     17 
141 13     27     10.3 76   9     18 
142 24    238     10.3 68   9     19 
143 16    201      8.0 82   9     20 
144 13    238     12.6 64   9     21 
145 23     14      9.2 71   9     22 
146 36    139     10.3 81   9     23 
147  7     49     10.3 69   9     24 
148 14     20     16.6 63   9     25 
149 30    193      6.9 70   9     26 
151 14    191     14.3 75   9     28 
152 18    131      8.0 76   9     29 
153 20    223     11.5 68   9     30

#### na.omit() function with specific column of the data

In [41]:
dfa <- na.omit(df$Ozone)

In [42]:
dfa

[1]  41  36  12  18  28  23  19   8   7  16  11  14  18  14  34   6  30  11
 [19]   1  11   4  32  23  45 115  37  29  71  39  23  21  37  20  12  13 135
 [37]  49  32  64  40  77  97  97  85  10  27   7  48  35  61  79  63  16  80
 [55] 108  20  52  82  50  64  59  39   9  16  78  35  66 122  89 110  44  28
 [73]  65  22  59  23  31  44  21   9  45 168  73  76 118  84  85  96  78  73
 [91]  91  47  32  20  23  21  24  44  21  28   9  13  46  18  13  24  16  13
[109]  23  36   7  14  30  14  18  20
attr(,"na.action")
 [1]   5  10  25  26  27  32  33  34  35  36  37  39  42  43  45  46  52  53  54
[20]  55  56  57  58  59  60  61  65  72  75  83  84 102 103 107 115 119 150
attr(,"class")
[1] "omit"

# Log() and Log10() Functions in R

**Syntax of log() function**

log() and log10(): The log function computes the natural log (Ln) and if the base is given, it will compute with base. On the other hand, the log10() function computes the common log (Lg).

**log(x,base=b)**

X = Input value.
<br>
Base = If mentioned, log value will be computed with base.

In [43]:
#Computes the logarithmic value of an input number
log(2)

[1] 0.6931472

In [44]:
log(5.2)

[1] 1.648659

In [45]:
log(16,base=2)

[1] 4

#### A simple log10() function

In [46]:
log10(5)

[1] 0.69897

In [47]:
#Computes the common log for the input values (decimal)
log10(123.567)

[1] 2.091903

In [48]:
df<-c(23,45,6.7,55,88.9,4,3.789)
 
#Computes the log value 
log(df)

[1] 3.135494 3.806662 1.902108 4.007333 4.487512 1.386294 1.332102

In [49]:
df<-c(23,45,6.7,55,88.9,4,3.789)
 
#Computes the log value 
log(df,base=2)

[1] 4.523562 5.491853 2.744161 5.781360 6.474112 2.000000 1.921817

In [50]:
#Creates a vector with values 
df<-c(23,45,6.7,55,88.9,4,3.789)
 
#Computes the log value 
log10(df)

[1] 1.3617278 1.6532125 0.8260748 1.7403627 1.9489018 0.6020600 0.5785246

#### log() and log10() functions with a dataframe

In [51]:
datasets::airquality

Ozone Solar.R Wind Temp Month Day
1    41   190      7.4 67   5      1 
2    36   118      8.0 72   5      2 
3    12   149     12.6 74   5      3 
4    18   313     11.5 62   5      4 
5    NA    NA     14.3 56   5      5 
6    28    NA     14.9 66   5      6 
7    23   299      8.6 65   5      7 
8    19    99     13.8 59   5      8 
9     8    19     20.1 61   5      9 
10   NA   194      8.6 69   5     10 
11    7    NA      6.9 74   5     11 
12   16   256      9.7 69   5     12 
13   11   290      9.2 66   5     13 
14   14   274     10.9 68   5     14 
15   18    65     13.2 58   5     15 
16   14   334     11.5 64   5     16 
17   34   307     12.0 66   5     17 
18    6    78     18.4 57   5     18 
19   30   322     11.5 68   5     19 
20   11    44      9.7 62   5     20 
21    1     8      9.7 59   5     21 
22   11   320     16.6 73   5     22 
23    4    25      9.7 61   5     23 
24   32    92     12.0 61   5     24 
25   NA    66     16.6 57   5     25 
26   NA   266     14.9 58   5     26 
27   NA    NA      8.0 57   5     27 
28   23    13     12.0 67   5     28 
29   45   252     14.9 81   5     29 
30  115   223      5.7 79   5     30 
... ...   ...     ...  ...  ...   ...
124 96    167      6.9 91   9      1 
125 78    197      5.1 92   9      2 
126 73    183      2.8 93   9      3 
127 91    189      4.6 93   9      4 
128 47     95      7.4 87   9      5 
129 32     92     15.5 84   9      6 
130 20    252     10.9 80   9      7 
131 23    220     10.3 78   9      8 
132 21    230     10.9 75   9      9 
133 24    259      9.7 73   9     10 
134 44    236     14.9 81   9     11 
135 21    259     15.5 76   9     12 
136 28    238      6.3 77   9     13 
137  9     24     10.9 71   9     14 
138 13    112     11.5 71   9     15 
139 46    237      6.9 78   9     16 
140 18    224     13.8 67   9     17 
141 13     27     10.3 76   9     18 
142 24    238     10.3 68   9     19 
143 16    201      8.0 82   9     20 
144 13    238     12.6 64   9     21 
145 23     14      9.2 71   9     22 
146 36    139     10.3 81   9     23 
147  7     49     10.3 69   9     24 
148 14     20     16.6 63   9     25 
149 30    193      6.9 70   9     26 
150 NA    145     13.2 77   9     27 
151 14    191     14.3 75   9     28 
152 18    131      8.0 76   9     29 
153 20    223     11.5 68   9     30

In [52]:
log(airquality$Temp[1:10])

[1] 4.204693 4.276666 4.304065 4.127134 4.025352 4.189655 4.174387 4.077537
 [9] 4.110874 4.234107

 top 10 values in the “Temp” column and the log() function returned the log values of the same. Let’s do the same using the log10()

In [53]:
log10(airquality$Temp[1:10])

[1] 1.826075 1.857332 1.869232 1.792392 1.748188 1.819544 1.812913 1.770852
 [9] 1.785330 1.838849

# Arrays in R

Arrays are data objects that can store data of multiple dimensions. In contrast to a matrix, arrays will store only one data type.

In [57]:
df1<- c(1,2,3)
df2<-c(2,4,6,8,10)
 

In [62]:
#creating 2 vectors
df1<- c(1,2,3)
df2<-c(2,4,6,8,10)
 
#Creating an array with dim parameter
df<- array(c(df1,df2),dim = c(3,3,2))
 
#display array
df

, , 1

     [,1] [,2] [,3]
[1,]    1    2    8
[2,]    2    4   10
[3,]    3    6    1

, , 2

     [,1] [,2] [,3]
[1,]    2    4   10
[2,]    3    6    1
[3,]    2    8    2

In [63]:
dfx

, , 1

     [,1] [,2] [,3]
[1,]    1    2    8
[2,]    2    4   10
[3,]    3    6    1

, , 2

     [,1] [,2] [,3]
[1,]    2    4   10
[2,]    3    6    1
[3,]    2    8    2

In [64]:
df[1,,1]

[1] 1 2 8

In [65]:
#return element present in first row, second column
df[1,2,2]

[1] 4

In [66]:
#Return first array
df[,,1]

[,1] [,2] [,3]
[1,] 1    2     8  
[2,] 2    4    10  
[3,] 3    6     1

In [67]:
#Returs the sum of first rows of all arrays
x <- apply(df, c(1), sum)

In [68]:
x

[1] 27 26 22